server:
  port: 9111
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
    max-connections: 10000
  servlet:
    context-path: /base

spring:
  profiles:
    include:
      - datasource
      - mybatis
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

logging:
  level:
    com:
      brucevon:
        base: debug

swagger2:
  enable: true
